import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import { ReactLenis } from "/src/lib/lenis.jsx";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Learnica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
      <html lang="en">
        <ReactLenis root>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
            <Navbar></Navbar>
            
            {children}

            {/* footer */}
            <Footer></Footer>
          </body>
        </ReactLenis>
      </html>
    </ClerkProvider>
  );
}
